/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestetud;

/**
 *
 * @author abdel
 */
public class ListeEtudiants extends javax.swing.JPanel {

    /**
     * Creates new form ListeEtudiant2
     */
    public ListeEtudiants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiants = new javax.swing.JTable();
        btnRecherche1 = new javax.swing.JButton();
        btnRecherche = new javax.swing.JButton();
        btnRecherche2 = new javax.swing.JButton();
        btnRecherche3 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRecherche.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRechercheFocusGained(evt);
            }
        });
        txtRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheActionPerformed(evt);
            }
        });
        jPanel1.add(txtRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 467, 36));

        tableEtudiants.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule", "Nom", "Prénom"
            }
        ));
        jScrollPane1.setViewportView(tableEtudiants);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 625, 370));

        btnRecherche1.setBackground(new java.awt.Color(0, 51, 255));
        btnRecherche1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRecherche1.setForeground(new java.awt.Color(255, 255, 255));
        btnRecherche1.setText("Recherche");
        btnRecherche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherche1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecherche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 6, 152, 36));

        btnRecherche.setBackground(new java.awt.Color(255, 0, 0));
        btnRecherche.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRecherche.setForeground(new java.awt.Color(255, 255, 255));
        btnRecherche.setText("Supprimer");
        btnRecherche.setEnabled(false);
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        btnRecherche2.setBackground(new java.awt.Color(0, 204, 0));
        btnRecherche2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRecherche2.setForeground(new java.awt.Color(255, 255, 255));
        btnRecherche2.setText("Modifier");
        btnRecherche2.setEnabled(false);
        btnRecherche2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherche2ActionPerformed(evt);
            }
        });

        btnRecherche3.setBackground(new java.awt.Color(0, 204, 0));
        btnRecherche3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRecherche3.setForeground(new java.awt.Color(255, 255, 255));
        btnRecherche3.setText("Actualiser");
        btnRecherche3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherche3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRecherche3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecherche2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecherche2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecherche3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void btnRecherche1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherche1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecherche1ActionPerformed

    private void btnRecherche2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherche2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecherche2ActionPerformed

    private void btnRecherche3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherche3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecherche3ActionPerformed

    private void txtRechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRechercheFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecherche;
    private javax.swing.JButton btnRecherche1;
    private javax.swing.JButton btnRecherche2;
    private javax.swing.JButton btnRecherche3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEtudiants;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
