/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestetud;

import classe.etudiant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdel
 */
public class ListeEtudiants extends javax.swing.JPanel {

    /**
     * Creates new form ListeEtudiant2
     */
    public ListeEtudiants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiants = new javax.swing.JTable();
        btnRecherche1 = new javax.swing.JButton();
        btnsupp = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();
        btnactu = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRecherche.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRechercheFocusGained(evt);
            }
        });
        txtRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheActionPerformed(evt);
            }
        });
        jPanel1.add(txtRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 467, 36));

        tableEtudiants.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule", "Nom", "Prénom"
            }
        ));
        tableEtudiants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEtudiantsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEtudiants);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 625, 370));

        btnRecherche1.setBackground(new java.awt.Color(0, 51, 255));
        btnRecherche1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRecherche1.setForeground(new java.awt.Color(255, 255, 255));
        btnRecherche1.setText("Recherche");
        btnRecherche1.setEnabled(false);
        btnRecherche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherche1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecherche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 6, 152, 36));

        btnsupp.setBackground(new java.awt.Color(255, 0, 0));
        btnsupp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnsupp.setForeground(new java.awt.Color(255, 255, 255));
        btnsupp.setText("Supprimer");
        btnsupp.setEnabled(false);
        btnsupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuppActionPerformed(evt);
            }
        });

        btnmodif.setBackground(new java.awt.Color(0, 204, 0));
        btnmodif.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnmodif.setForeground(new java.awt.Color(255, 255, 255));
        btnmodif.setText("Modifier");
        btnmodif.setEnabled(false);
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });

        btnactu.setBackground(new java.awt.Color(0, 204, 0));
        btnactu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnactu.setForeground(new java.awt.Color(255, 255, 255));
        btnactu.setText("Actualiser");
        btnactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnactu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsupp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsupp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheActionPerformed

    private void btnsuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuppActionPerformed
        // TODO add your handling code here:
        String matricule=tableEtudiants.getValueAt(tableEtudiants.getSelectedRow(),0).toString();
        int matri = Integer.parseInt(matricule);
        try {
            etudiant.supprimer(matri);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListeEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnmodif.setEnabled(false);
        btnsupp.setEnabled(false);
        DefaultTableModel tm=(DefaultTableModel) tableEtudiants.getModel();
        tm.setRowCount(0);
        etudiant.actualiser(tm);
    }//GEN-LAST:event_btnsuppActionPerformed

    private void btnRecherche1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherche1ActionPerformed
        // TODO add your handling code here:
        
        String matricule= txtRecherche.getText();
        int matri =Integer.parseInt(matricule);
        DefaultTableModel tm=(DefaultTableModel) tableEtudiants.getModel();
        tm.setRowCount(0);
        etudiant.recherche(matri,tm);
    }//GEN-LAST:event_btnRecherche1ActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
        modification2 mod =new modification2();
       String matricule=tableEtudiants.getValueAt(tableEtudiants.getSelectedRow(),0).toString();
       String nom=tableEtudiants.getValueAt(tableEtudiants.getSelectedRow(),1).toString();
       String prenom=tableEtudiants.getValueAt(tableEtudiants.getSelectedRow(),2).toString();
       
       mod.setmatricule(matricule);
       mod.setnom(nom);
       mod.setprenom(prenom);
       mod.setVisible(true);
       
        
        
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel) tableEtudiants.getModel();
        tm.setRowCount(0);
        etudiant.actualiser(tm);
        btnsupp.setEnabled(false);
        btnmodif.setEnabled(false);
    }//GEN-LAST:event_btnactuActionPerformed

    private void txtRechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRechercheFocusGained
        // TODO add your handling code here:
        btnmodif.setEnabled(false);
        btnsupp.setEnabled(false);
        btnRecherche1.setEnabled(true);
    }//GEN-LAST:event_txtRechercheFocusGained

    private void tableEtudiantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEtudiantsMouseClicked
        // TODO add your handling code here:
        if(tableEtudiants.getRowCount()!=0)
        {
            btnmodif.setEnabled(true);
            btnsupp.setEnabled(true);
        }
    }//GEN-LAST:event_tableEtudiantsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecherche1;
    private javax.swing.JButton btnactu;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsupp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEtudiants;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
